<a href="https://colab.research.google.com/github/Sauvi72/Data_sci_Python/blob/main/lec_08_pandas_%7C%7C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [6]:
import pandas as pd

# Option A: Adding a 5th element to match the 5 IDs
df1 = pd.DataFrame({
    'id'   : [1, 2, 3, 4, 5],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'], # Added 'amit'
    'age'  : [25, 30, 45, 67, 28]                       # Added 28
})

df2 = pd.DataFrame({
    'id'   : [3, 4, 5, 6, 7],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'], # Added 'amit'
    'age'  : [25, 32, 45, 60, 28]                       # Added 28
})

# Now the inner join will work perfectly {on common ids}

df3 = pd.merge(df1, df2, on='id', how='inner')
df3.rename(columns={'name_x': 'table_name_1', 'name_y': 'table_name_2'}, inplace=True)


print(df3)

   id table_name_1  age_x table_name_2  age_y
0   3        sauvi     45         raja     25
1   4         rhea     67         rani     32
2   5         amit     28        sauvi     45

In [7]:
import pandas as pd

df1 = pd.DataFrame({
    'id'   : [1, 2, 3, 4, 5],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 30, 45, 67, 28]
})

df2 = pd.DataFrame({
    'id'   : [3, 4, 5, 6, 7],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 32, 45, 60, 28]
})


df3 = pd.merge(df1, df2, on='id', how='left')        #list down the left table data whether foun din right or not liste NaN ;
df3.rename(columns={'name_x': 'table_name_1', 'name_y': 'table_name_2'}, inplace=True)


print(df3)

   id table_name_1  age_x table_name_2  age_y
0   1         raja     25          NaN    NaN
1   2         rani     30          NaN    NaN
2   3        sauvi     45         raja   25.0
3   4         rhea     67         rani   32.0
4   5         amit     28        sauvi   45.0

In [8]:
import pandas as pd

#right joins

df1 = pd.DataFrame({
    'id'   : [1, 2, 3, 4, 5],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 30, 45, 67, 28]
})

df2 = pd.DataFrame({
    'id'   : [3, 4, 5, 6, 7],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 32, 45, 60, 28]
})


df3 = pd.merge(df1, df2, on='id', how='right')
df3.rename(columns={'name_x': 'table_name_1', 'name_y': 'table_name_2'}, inplace=True)


print(df3)

   id table_name_1  age_x table_name_2  age_y
0   3        sauvi   45.0         raja     25
1   4         rhea   67.0         rani     32
2   5         amit   28.0        sauvi     45
3   6          NaN    NaN         rhea     60
4   7          NaN    NaN         amit     28

In [9]:
import pandas as pd
#outer joins
df1 = pd.DataFrame({
    'id'   : [1, 2, 3, 4, 5],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 30, 45, 67, 28]
})

df2 = pd.DataFrame({
    'id'   : [3, 4, 5, 6, 7],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 32, 45, 60, 28]
})


df3 = pd.merge(df1, df2, on='id', how='outer')
df3.rename(columns={'name_x': 'table_name_1', 'name_y': 'table_name_2'}, inplace=True)


print(df3)

   id table_name_1  age_x table_name_2  age_y
0   1         raja   25.0          NaN    NaN
1   2         rani   30.0          NaN    NaN
2   3        sauvi   45.0         raja   25.0
3   4         rhea   67.0         rani   32.0
4   5         amit   28.0        sauvi   45.0
5   6          NaN    NaN         rhea   60.0
6   7          NaN    NaN         amit   28.0

In [12]:
#cross joins

import pandas as pd

df1 = pd.DataFrame({
    'id'   : [1, 2, 3, 4, 5],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 30, 45, 67, 28]
})

df2 = pd.DataFrame({
    'id'   : [3, 4, 5, 6, 7],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 32, 45, 60, 28]
})


df3 = pd.merge(df1, df2, how='cross')
df3.rename(columns={'name_x': 'table_name_1', 'name_y': 'table_name_2'}, inplace=True)


print(df3)

    id_x table_name_1  age_x  id_y table_name_2  age_y
0      1         raja     25     3         raja     25
1      1         raja     25     4         rani     32
2      1         raja     25     5        sauvi     45
3      1         raja     25     6         rhea     60
4      1         raja     25     7         amit     28
5      2         rani     30     3         raja     25
6      2         rani     30     4         rani     32
7      2         rani     30     5        sauvi     45
8      2         rani     30     6         rhea     60
9      2         rani     30     7         amit     28
10     3        sauvi     45     3         raja     25
11     3        sauvi     45     4         rani     32
12     3        sauvi     45     5        sauvi     45
13     3        sauvi     45     6         rhea     60
14     3        sauvi     45     7         amit     28
15     4         rhea     67     3         raja     25
16     4         rhea     67     4         rani     32
17     4         rhea     67     5        sauvi     45
18     4         rhea     67     6         rhea     60
19     4         rhea     67     7         amit     28
20     5         amit     28     3         raja     25
21     5         amit     28     4         rani     32
22     5         amit     28     5        sauvi     45
23     5         amit     28     6         rhea     60
24     5         amit     28     7         amit     28

In [14]:
#concatination
import pandas as pd
#outer joins
df1 = pd.DataFrame({
    'id'   : [1, 2, 3, 4, 5],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 30, 45, 67, 28]
})

df2 = pd.DataFrame({
    'id'   : [3, 4, 5, 6, 7],
    'name' : ['raja', ' rani', 'sauvi', 'rhea', 'amit'],
    'age'  : [25, 32, 45, 60, 28]
})


df3 = pd.concat([df1, df2])


display(df3)

   id   name  age
0   1   raja   25
1   2   rani   30
2   3  sauvi   45
3   4   rhea   67
4   5   amit   28
0   3   raja   25
1   4   rani   32
2   5  sauvi   45
3   6   rhea   60
4   7   amit   28

In [22]:
#drop_duplicates() -- > applied on dataframe


df = pd.DataFrame(
    {
        "id": [1, 2, 2, 3, 3],
        "name": ["raja", "rani", "rani", "sauvi", "sauvi"],
        "age": [25, 30, 30, 45, 45],
    }
)

# df3 = df.drop_duplicates(subset = ['id'] , keep = 'first' )

df3 = df.drop_duplicates(subset = ['id' , 'name'] , keep = 'first' ) #==========> id & name when become similar together then it work







display(df3)

   id   name  age
0   1   raja   25
1   2   rani   30
3   3  sauvi   45

In [23]:

#convert column to datetime

df = pd.DataFrame(
    {
        "date_str": ["2026-01-15", "2026-02-20", "2026-03-05"],
        "sales": [100, 150, 200],
    }
)

df["date"] = pd.to_datetime(df["date_str"])

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day_name()

print(df)

     date_str  sales       date  year  month       day
0  2026-01-15    100 2026-01-15  2026      1  Thursday
1  2026-02-20    150 2026-02-20  2026      2    Friday
2  2026-03-05    200 2026-03-05  2026      3  Thursday

In [24]:
df = pd.DataFrame(
    {
        "date": [
            "2026-01-01",
            "2026-01-01",
            "2026-01-01",
            "2026-01-02",
            "2026-01-02",
        ],
        "city": ["Delhi", "Delhi", "Mumbai", "Delhi", "Mumbai"],
        "sales": [100, 150, 200, 120, 250],
    }
)

df3 = df.pivot_table(
    index="date", columns="city", values="sales", aggfunc="sum"
)

print(df3)

city        Delhi  Mumbai
date
2026-01-01    250     200
2026-01-02    120     250

In [26]:
df = pd.read_csv('student_data.csv')

In [27]:
#pivot table
df.pivot_table(columns = 'placement_status', index = 'sleep_hours', values = 'exam_score' , aggfunc = 'mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [28]:
#pivot table
df.pivot_table(columns = 'study_hours', index = 'sleep_hours', values = 'assignments_completed' , aggfunc = 'mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844

In [ ]:
# End of Pandas