<a href="https://colab.research.google.com/github/Sauvi72/Data_sci_Python/blob/main/lec_06_pandas_%7C%7C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
import numpy as np

dct = {
    'name':['tom' ,'nick' , 'krish' , 'jack'],
    'age':[20 , 21 , 19 , 18] ,
    'roll': [1,2,3,4]
}


df = pd.DataFrame(dct)
d = pd.DataFrame(dct, index = ['a','b','c','d'])


display(df)
print()
display(d)

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

    name  age  roll
a    tom   20     1
b   nick   21     2
c  krish   19     3
d   jack   18     4

In [10]:
df = pd.read_csv('student_data.csv')
print(df)
print()
df.tail(3)
print()
df.info()

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [21]:
df = pd.read_csv('student_data.csv')
# print(df)
print()
# df.tail(3)
# print()
#df.index
# print()

#df[['study_hours' , 'internet_usage']]
#df[['study_hours', 'internet_usage']]

#df.loc[df['study_hours']==11 , ['study_hours' , 'sleep_hours']].iloc[4:8]

df2 = df.loc[df['study_hours']== 11]

print()

df2[['study_hours' , 'sleep_hours']]

      study_hours  sleep_hours
2              11            7
9              11            4
10             11            8
29             11            9
30             11            5
...           ...          ...
9969           11            8
9971           11            9
9978           11            8
9979           11            9
9988           11            6

[868 rows x 2 columns]

In [29]:
df = pd.read_csv('student_data.csv')
df.loc[df['assignments_completed'] == 8].iloc[1]

# df['assignments_completed' == 8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [31]:
df = pd.read_csv('student_data.csv')

df[df['assignments_completed'] > 3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [38]:
df = pd.read_csv('student_data.csv')

df.loc[df['assignments_completed'] > 3, 'age'] = 20

df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20.0
1,4,69,5,3,8,56,100.00,Placed,20.0
2,11,60,7,6,10,45,100.00,Placed,20.0
3,8,99,9,8,4,55,90.17,Placed,20.0
4,5,52,8,6,8,40,78.82,Placed,20.0
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20.0
9996,7,98,6,9,4,87,100.00,Placed,20.0
9997,10,44,8,5,10,37,95.94,Placed,20.0
9998,10,75,7,5,8,52,88.61,Placed,20.0
9999,2,70,6,11,16,52,78.96,Placed,20.0

In [36]:
df = pd.read_csv('student_data.csv')

# rename columns
df = df.rename(columns={'assignments_completed': 'assign_completed'})

df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [52]:
df = pd.read_csv('student_data.csv')

#drop()
df = df.drop('assignments_completed', axis=1)            # delete the whole column of ASSIGNMENTS_COMPLETED
# df = df.drop(1, axis=0)                                  # delete the selected row

df

,study_hours,attendance,sleep_hours,internet_usage,previous_score,exam_score,placement_status
0,7,56,8,7,62,100.00,Placed
1,4,69,5,3,56,100.00,Placed
2,11,60,7,6,45,100.00,Placed
3,8,99,9,8,55,90.17,Placed
4,5,52,8,6,40,78.82,Placed
...,...,...,...,...,...,...,...
9995,2,58,9,7,88,69.31,Not Placed
9996,7,98,6,9,87,100.00,Placed
9997,10,44,8,5,37,95.94,Placed
9998,10,75,7,5,52,88.61,Placed
9999,2,70,6,11,52,78.96,Placed

In [55]:
#dopna() --------> remove the null value from the data


df = pd.read_csv('student_data.csv')
df.dropna(axis=0)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')

df.sort_values()

In [63]:

data = {
    "name": ["sauvi", "Riya", "Vikram", "Neha", "Arjun"],
    "age": [20, 21, np.nan, 19, 22],
    "marks": [85, np.nan, 78, 90, 88],
    "assignments_completed": [5, 2, 4, np.nan, 6]
}

df = pd.DataFrame(data)

# print(df)

# df = df.dropna()
print(df)

     name   age  marks  assignments_completed
0   sauvi  20.0   85.0                    5.0
1    Riya  21.0    NaN                    2.0
2  Vikram   NaN   78.0                    4.0
3    Neha  19.0   90.0                    NaN
4   Arjun  22.0   88.0                    6.0

In [ ]:
# Function	 Meaning

# isnull() ->  missing values check
# notnull()->  not missing values
# unique() ->  all distinct values
# nunique()->  count of unique values

In [64]:
data = {
    "name": ["Aman", "Riya", "Vikram", None],
    "marks": [85, np.nan, 78, 90]
}

df = pd.DataFrame(data)

print(df.isnull())
df['marks'].nunique()
# print(df['marks'].unique())

df.isnull().sum()               #----> Count missing values
df[df['marks'].notnull()]               #-> Keep only non-null rows

    name  marks
0  False  False
1  False   True
2  False  False
3   True  False